sudo: false
dist: trusty
language: php
services:
  - mysql
cache:
  apt: true
env:
  global:
  - EE_VERSION=master
  - WP_VERSION=latest WP_MULTISITE=0
matrix:
  include:
  - php: 5.5
  - php: 5.6
  - php: 5.6
    env: WP_MULTISITE=1
  - php: 5.6
    env: WP_VERSION=4.2
  - php: 5.6
    env: WP_VERSION=4.2 WP_MULTISITE=1
  - php: 7.0
  - php: 7.1
  - php: 7.2
  fast_finish: true
before_install:
- |
  if [[ "$SKIP_XDEBUG_REMOVE" != "true" ]]; then
    phpenv config-rm xdebug.ini
    echo "xdebug removed";
  fi
before_script:
- bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- . tests/bin/setup-addon-tests.sh
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
    # Install the specified version of PHPUnit depending on the PHP version:
    if [[ -n "$TRAVIS_PHP_VERSION" ]]; then
      case "$TRAVIS_PHP_VERSION" in
        7.2|7.1|7.0|nightly)
          echo "Using PHPUnit 6.1"
          composer global require "phpunit/phpunit=6.1.*"
          ;;
        5.6|5.5|5.4|5.3)
          echo "Using PHPUnit 4.8"
          composer global require "phpunit/phpunit=4.8.*"
          ;;
        5.2)
          # Do nothing, use default PHPUnit 3.6.x
          echo "Using default PHPUnit, hopefully 3.6"
          ;;
        *)
          echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
          exit 1
          ;;
      esac
    fi
- mysql --version
- phpunit --version
- phpenv versions
script: cd tests; phpunit;
notifications:
  slack:
    rooms:
      secure: "DyvcDWIx+ULdgVHEQ+1vG0icJAjaHIV7MBUTXzKtK1m3kGlVh54NsUnqhJd9C/Ufcx4AUPDaPi02snmv3JPfhxC9c9DnKYbcivxSTdasR4rBjnqU/W7UronPprm0mIG5kQMfU3uEFO3gueyanWMY/ntS2qz/chQD9MWmVoiVMAKLIhTJrCK1jbbUB9xT73S3i0OwSad9ZdMwVFYCDPRpxKwv+mN0W4sX4dOu5STNbelM4tYA+Omf96RlmSnDktPYZ7EEbLB1MFc709IIHhhEWybZ78RgO2kSl7JD17FSM0Ot/UuMuKAujFr96dmz5A66Ua7JMLyqGhp5vvz1Hp7HGyT3kxla5GKbB2Jw91G5rhMo43g7Aq5XwevRKQbGu7hg7BEbR+vXvSjYIu5HZIyUwXTcRnjW0M5jYatDOhhgu0WR7w64VWrLuqg3dG0CKjitN6HNAFDqwmbppiCwLtT7KKt6BtDPssoIiUZj0Qvu4JhIYYMsfKHvvSIZ5R9eXNNfGgZqKrpQQHIhvemXpr42ODwDWnNrsAeE7fPKdeFeWg0aAoap/kx805AeqnpVDfBCxo/4WkQXtE3neExqVLjBrdQWTCJzwOoNwsvirMJZy6ns4b68Fp/QGvONJEY5MH55mE9jYicuL8wIpJQJgU9lQRzmdseauvzNwr2HbPsxArU="
    on_success: always
    on_failure: always
    on_start: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "%{commit_message}"
